#!/usr/bin/env bash
# Regenerate the CLI-driven collision-matrix corpus (CM-*) by scripting the REAL
# pinned skills CLI (skills@1.5.26) and gh in isolated sandbox HOMEs.
#
# Scenarios (docs/collision-matrix.md, architecture D17):
#   CM-1  npx copy-mode baseline
#   CM-2  gh exact-path baseline
#   CM-3  double-booked + drift + divergence (npx then gh --force)
#   CM-5  reverse double-booked (gh then npx add -y erases gh provenance)
#   CM-6  dangerous-removal pre-state (gh-owned + ownerless, no vercel lock)
#   CM-8  mixed install (one name, three placements, two partial ledgers)
#
# Properties:
#   - re-runnable (each CM dir is wiped and rebuilt);
#   - every CM dir records the CLI pin (PIN.txt) and ships an EXPECTATION.md;
#   - network use is gated behind SUKIRU_E2E=1;
#   - a real-$HOME canary asserts the user's home is never mutated;
#   - GENERATOR HYGIENE: the sandbox .home is generator scratch. The pinned
#     skills CLI writes a global v3 lock into it even for purely
#     project-scope installs, which would scan back as a SPURIOUS user-scope
#     lock-without-files finding; npm/mise also stash caches there. Every
#     scenario ends with finalize_fixture, which resets .home to a pristine
#     empty dir (.gitkeep) and removes the CLI transcripts — the committed
#     corpus carries provenance in PIN.txt + EXPECTATION.md only (same idiom
#     as generate-hash-parity.sh).
#
# Usage:
#   Scripts/fixtures/generate.sh --check              # verify tooling+plumbing, no network
#   SUKIRU_E2E=1 GH_TOKEN="$(gh auth token)" \
#     Scripts/fixtures/generate.sh [TARGET_DIR]       # full generation
#
# TARGET_DIR defaults to <repo>/Fixtures.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
# shellcheck source=lib.sh
source "$SCRIPT_DIR/lib.sh"

# Source repo + test skill used across the matrix (docs/collision-matrix.md).
SRC_REPO="thedavidweng/skills"
SKILL_NAME="stale-docs-cleanup"
SKILL_PATH="maintenance/stale-docs-cleanup/SKILL.md"

MODE="generate"
TARGET="$REPO_ROOT/Fixtures"
case "${1:-}" in
    --check) MODE="check" ;;
    "") : ;;
    *) TARGET="$1" ;;
esac
mkdir -p "$TARGET"

# --- preflight -------------------------------------------------------------
preflight() {
    local ok=1
    if [ -z "$NPX_BIN" ]; then echo "missing: npx" >&2; ok=0; fi
    if [ -z "$GH_BIN" ]; then echo "missing: gh" >&2; ok=0; fi
    [ "$ok" = 1 ] || { echo "preflight failed: install missing tools" >&2; exit 2; }
    echo "npx: $NPX_BIN"
    echo "gh:  $GH_BIN"
    echo "pin: $SKILLS_PIN"
}

if [ "$MODE" = "check" ]; then
    preflight
    canary_capture
    sb="$(make_sandbox "$TARGET" ".check-sandbox")"
    echo "sandbox ok: $sb (real HOME: $REAL_HOME)"
    canary_assert_unchanged
    rm -rf "$TARGET/.check-sandbox"
    echo "check OK — tooling present, sandbox isolated, canary intact."
    exit 0
fi

require_e2e
preflight
canary_capture

# finalize_fixture DIR HOME — reset the sandbox home to a pristine empty dir
# (.gitkeep so git tracks it; the scan suite keys on .home existing) and drop
# the CLI transcripts. Without this, the CLI-written sandbox global lock and
# the npm/mise caches would be committed and CM scans would report a spurious
# user-scope lock-without-files finding.
finalize_fixture() {
    local dir="$1" home="$2"
    force_rm_rf "$home"
    mkdir -p "$home"
    : >"$home/.gitkeep"
    rm -f "$dir/proj/.skills.out" "$dir/proj/.skills.err" \
          "$dir/proj/.gh.out" "$dir/proj/.gh.err"
}

# =====================================================================
# CM-1 — npx copy-mode baseline (project scope).
# =====================================================================
cm1() {
    local dir="$TARGET/CM-1"; local home proj
    home="$(make_sandbox "$TARGET" "CM-1")"
    proj="$dir/proj"; mkdir -p "$proj"
    # Two targets (codex -> canonical .agents/skills, claude-code -> .claude/skills)
    # with --copy forces two PHYSICAL copies: the exact cross-host duplicate shape.
    run_skills "$home" "$proj" add "$SRC_REPO" -s "$SKILL_NAME" -a claude-code -a codex --copy -y
    finalize_fixture "$dir" "$home"
    record_pin "$dir"
    cat >"$dir/EXPECTATION.md" <<EOF
# CM-1 — npx copy-mode baseline

Generated by:
\`npx $SKILLS_PIN add $SRC_REPO -s $SKILL_NAME -a claude-code -a codex --copy -y\`
in the sandbox project \`proj/\` (codex resolves to the canonical .agents/skills,
claude-code to .claude/skills; --copy forces two physical copies). Scan with
SUKIRU_HOME=<CM-1>/.home, SUKIRU_ROOTS=<CM-1>/proj.

Expect (VAL-SCAN-043): ownership=vercel for \`$SKILL_NAME\`; project v1 lock
\`proj/skills-lock.json\` with source/sourceType/skillPath/computedHash; two
placements — canonical \`.agents/skills\` + \`.claude/skills\` physical copy —
as an EXACT cross-host duplicate (same hash, distinct paths). NO drift, NO
double-booked, NO files-without-lock.
EOF
    echo "CM-1 done"
}

# =====================================================================
# CM-2 — gh exact-path baseline (host dir only, no lock).
# =====================================================================
cm2() {
    local dir="$TARGET/CM-2"; local home proj
    home="$(make_sandbox "$TARGET" "CM-2")"
    proj="$dir/proj"; mkdir -p "$proj/.claude/skills"
    run_gh "$home" "$proj" skill install "$SRC_REPO" "$SKILL_PATH" --force --dir "$proj/.claude/skills"
    finalize_fixture "$dir" "$home"
    record_pin "$dir"
    cat >"$dir/EXPECTATION.md" <<EOF
# CM-2 — gh exact-path baseline

Generated by: \`gh skill install $SRC_REPO $SKILL_PATH --force --dir proj/.claude/skills\`.
Scan with SUKIRU_HOME=<CM-2>/.home, SUKIRU_ROOTS=<CM-2>/proj.

Expect (VAL-SCAN-044): ownership=github; frontmatter github-{repo,path,ref,tree-sha}
with ref=refs/heads/main; NO lock file; NO vercel-lock-drift; NO files-without-lock
(gh provenance satisfies the ledger); a \`dangerous-removal-surface\` advisory
(gh-owned).
EOF
    echo "CM-2 done"
}

# =====================================================================
# CM-3 — double-booked + drift + divergence: npx install, then gh --force over
# the .claude copy (vercel lock stays stale; canonical untouched).
# =====================================================================
cm3() {
    local dir="$TARGET/CM-3"; local home proj
    home="$(make_sandbox "$TARGET" "CM-3")"
    proj="$dir/proj"; mkdir -p "$proj"
    # Copy install both canonical (.agents via codex) and the .claude host copy...
    run_skills "$home" "$proj" add "$SRC_REPO" -s "$SKILL_NAME" -a claude-code -a codex --copy -y
    # ...then gh --force overwrites ONLY the .claude copy (canonical + lock stay stale).
    run_gh "$home" "$proj" skill install "$SRC_REPO" "$SKILL_PATH" --force --dir "$proj/.claude/skills"
    finalize_fixture "$dir" "$home"
    record_pin "$dir"
    cat >"$dir/EXPECTATION.md" <<EOF
# CM-3 — double-booked + drift + divergence

Generated by: npx copy install, THEN \`gh skill install --force\` over the
\`.claude\` copy (vercel lock left stale; canonical \`.agents\` untouched).
Scan with SUKIRU_HOME=<CM-3>/.home, SUKIRU_ROOTS=<CM-3>/proj.

Expect (VAL-SCAN-045) — three concurrent symptoms:
1. ownership=double-booked + a \`double-booked\` finding (both-ledger evidence);
2. \`vercel-lock-drift\` (lock computedHash stale vs the overwritten .claude copy);
3. \`canonical-host-divergence\` (canonical vs host copy hash mismatch, one source identity).
All three with full evidence.
EOF
    echo "CM-3 done"
}

# =====================================================================
# CM-5 — reverse double-booked: gh install first, then npx add -y (overwrites
# host copy, erases gh provenance, writes a vercel lock entry).
# =====================================================================
cm5() {
    local dir="$TARGET/CM-5"; local home proj
    home="$(make_sandbox "$TARGET" "CM-5")"
    proj="$dir/proj"; mkdir -p "$proj/.claude/skills"
    run_gh "$home" "$proj" skill install "$SRC_REPO" "$SKILL_PATH" --force --dir "$proj/.claude/skills"
    run_skills "$home" "$proj" add "$SRC_REPO" -s "$SKILL_NAME" -a claude-code --copy -y
    finalize_fixture "$dir" "$home"
    record_pin "$dir"
    cat >"$dir/EXPECTATION.md" <<EOF
# CM-5 — reverse double-booked (provenance erased)

Generated by: \`gh skill install\` first, THEN \`npx $SKILLS_PIN add -y\`, which
overwrites the host copy, silently ERASES the gh frontmatter provenance, and
writes a vercel lock entry. Scan with SUKIRU_HOME=<CM-5>/.home,
SUKIRU_ROOTS=<CM-5>/proj.

Expect (VAL-SCAN-046): ownership=vercel; NO github provenance anywhere
(documents the silent erasure as observable fact); NO double-booked finding
(the gh ledger claim is gone from disk).
EOF
    echo "CM-5 done"
}

# =====================================================================
# CM-6 — dangerous-removal pre-state: a gh-owned skill plus an ownerless copy in
# a host dir, no vercel lock (the state BEFORE `npx skills remove` would strike).
# =====================================================================
cm6() {
    local dir="$TARGET/CM-6"; local home proj
    home="$(make_sandbox "$TARGET" "CM-6")"
    proj="$dir/proj"; mkdir -p "$proj/.claude/skills"
    run_gh "$home" "$proj" skill install "$SRC_REPO" "$SKILL_PATH" --force --dir "$proj/.claude/skills"
    # An ownerless copy alongside (no ledger of any kind): copy the gh skill dir
    # and strip its provenance frontmatter block's github-* lines.
    if [ -d "$proj/.claude/skills/$SKILL_NAME" ]; then
        cp -R "$proj/.claude/skills/$SKILL_NAME" "$proj/.claude/skills/orphaned-copy"
        # Remove github-* provenance to make it ownerless.
        sed -i '' '/github-/d' "$proj/.claude/skills/orphaned-copy/SKILL.md" 2>/dev/null || \
            sed -i '/github-/d' "$proj/.claude/skills/orphaned-copy/SKILL.md"
    fi
    finalize_fixture "$dir" "$home"
    record_pin "$dir"
    cat >"$dir/EXPECTATION.md" <<EOF
# CM-6 — dangerous-removal pre-state

Generated by: \`gh skill install\` (gh-owned \`$SKILL_NAME\`) plus a hand-derived
ownerless copy \`orphaned-copy\` (github-* lines stripped), in \`.claude/skills\`,
with NO vercel lock. Scan with SUKIRU_HOME=<CM-6>/.home, SUKIRU_ROOTS=<CM-6>/proj.

Expect (VAL-SCAN-030): a \`dangerous-removal-surface\` advisory for BOTH the
gh-owned skill and the ownerless copy (each deletable by name via
\`npx skills remove\`). This is collision-matrix scenario 6 before removal.
EOF
    echo "CM-6 done"
}

# =====================================================================
# CM-8 — mixed install: one name, three physical placements, two partial ledgers.
# gh owns the .claude copy; npx's lock claims the canonical copy; a third
# copy in .qoder is byte-identical to the canonical one.
# =====================================================================
cm8() {
    local dir="$TARGET/CM-8"; local home proj
    home="$(make_sandbox "$TARGET" "CM-8")"
    proj="$dir/proj"; mkdir -p "$proj"
    # npx copy install -> canonical .agents copy + .claude copy + v1 lock
    run_skills "$home" "$proj" add "$SRC_REPO" -s "$SKILL_NAME" -a claude-code -a codex --copy -y
    # gh --force over the .claude copy -> gh owns that placement
    run_gh "$home" "$proj" skill install "$SRC_REPO" "$SKILL_PATH" --force --dir "$proj/.claude/skills"
    # third ownerless copy in a DISTINCT host dir (.qoder/skills has its own path)
    mkdir -p "$proj/.qoder/skills"; : >"$proj/.qoder/.marker"
    if [ -d "$proj/.agents/skills/$SKILL_NAME" ]; then
        cp -R "$proj/.agents/skills/$SKILL_NAME" "$proj/.qoder/skills/$SKILL_NAME"
        sed -i '' '/github-/d' "$proj/.qoder/skills/$SKILL_NAME/SKILL.md" 2>/dev/null || \
            sed -i '/github-/d' "$proj/.qoder/skills/$SKILL_NAME/SKILL.md" || true
    fi
    finalize_fixture "$dir" "$home"
    record_pin "$dir"
    cat >"$dir/EXPECTATION.md" <<EOF
# CM-8 — mixed install (three-source resolution)

Generated by: npx copy install (canonical + .claude copy + v1 lock), THEN
\`gh skill install --force\` over the .claude copy (gh owns it), PLUS a third
copy in \`.qoder/skills\` byte-identical to the canonical one. One name, three
physical placements, two partial ledgers. Scan with SUKIRU_HOME=<CM-8>/.home,
SUKIRU_ROOTS=<CM-8>/proj.

Expect (VAL-SCAN-047, D23): all three placements surfaced with correct
kinds/paths. The .qoder copy is hash-explained by the lock-anchored canonical
placement and the .claude copy carries gh frontmatter, so NO placement is
unexplained and the name is NOT ambiguous — NO \`ambiguous-name\` finding.
Ownership resolves double-booked with BOTH ledger claims (vercel lock + gh
provenance) surfaced as data. Findings: \`double-booked\`,
\`vercel-lock-drift\` on the .claude placement, \`canonical-host-divergence\`
(.claude vs canonical), and an exact-subtype \`cross-host-duplicate\` for the
.qoder/canonical pair.
EOF
    echo "CM-8 done"
}

cm1
cm2
cm3
cm5
cm6
cm8

# Final hygiene sweep: belt-and-braces reset of every sandbox home once all
# CLI processes are long dead, in case a detached writer (update notifier,
# cache flusher) outlived its parent past the per-scenario finalize.
for cm in CM-1 CM-2 CM-3 CM-5 CM-6 CM-8; do
    finalize_fixture "$TARGET/$cm" "$TARGET/$cm/.home"
done

canary_assert_unchanged
echo "CM-* corpus regenerated under: $TARGET"
