// Ground-truth generator for Sukiru's Rust-`Debug` symlink quoting.
//
// The archived Rust CLI hashes a symlink inside a skill dir as
// `format!("symlink:{target:?}")` where `target` is a `PathBuf`. This helper
// uses rustc itself as the oracle for what `{:?}` emits:
//
//   table    — sweep every Unicode scalar 0x0..=0x10FFFF through
//              `format!("{:?}", PathBuf::from(c.to_string()))` and emit the
//              Swift source of `RustDebugEscapes` (the inclusive ranges that
//              Debug renders as `\u{<lower-hex>}`, excluding the named
//              escapes \t \r \n \\ \" \0). Single quotes are asserted to pass
//              through literally.
//   battery  — print TSV rows `name <target-hex> <output-hex> <rust-literal>`
//              for a battery of adversarial symlink targets, where output is
//              the exact bytes of `format!("symlink:{target:?}")`.
//
// Build & run via Scripts/rust-debug/generate.sh (plain rustc, no crates).

use std::path::PathBuf;

const BATTERY: &[(&str, &str)] = &[
    ("plain", "target/one.md"),
    ("quote-backslash-squote", "we\"ird\\it's.md"),
    ("squote-only", "it's.md"),
    ("nul", "nul\0byte"),
    ("tab", "ta\tb"),
    ("cr", "ca\rr"),
    ("lf", "li\nne"),
    ("del", "del\u{7f}ete"),
    ("nel", "ne\u{85}l"),
    ("soft-hyphen", "so\u{ad}ft"),
    ("nfd-combining-acute", "re\u{301}sume\u{301}"),
    ("combining-only", "\u{301}\u{341}"),
    ("zwj", "a\u{200d}b"),
    ("zwnj", "a\u{200c}b"),
    ("bom", "a\u{feff}b"),
    ("nbsp", "a\u{a0}b"),
    ("line-separator", "a\u{2028}b"),
    ("paragraph-separator", "a\u{2029}b"),
    ("private-use", "a\u{e000}b"),
    ("unassigned", "a\u{378}b"),
    ("tag-char", "a\u{e0001}b"),
    ("cjk", "中文.md"),
    ("emoji", "crab 🦀.md"),
    ("astral-musical", "𝄞.md"),
];

fn hex(s: &str) -> String {
    s.bytes().map(|b| format!("{:02x}", b)).collect()
}

fn battery() {
    for (name, target) in BATTERY {
        let output = format!("symlink:{:?}", PathBuf::from(target));
        println!(
            "{}\t{}\t{}\t{:?}",
            name,
            hex(target),
            hex(&output),
            output
        );
    }
}

fn table(toolchain: &str) {
    // Escapes `ContentHasher.rustDebugQuotedSymlink` emits itself; everything
    // else that Debug escapes must be a `\u{...}` form.
    let named: [char; 6] = ['\t', '\r', '\n', '\\', '"', '\0'];
    let mut ranges: Vec<(u32, u32)> = Vec::new();
    let mut str_pathbuf_divergences = 0u64;
    for cp in 0u32..=0x10FFFF {
        let Some(c) = char::from_u32(cp) else { continue };
        let owned = c.to_string();
        let debug_pathbuf = format!("{:?}", PathBuf::from(owned.clone()));
        let debug_str = format!("{:?}", owned);
        if debug_pathbuf != debug_str {
            str_pathbuf_divergences += 1;
            eprintln!(
                "warning: PathBuf vs str Debug diverge at U+{:04X}: {} vs {}",
                cp, debug_pathbuf, debug_str
            );
        }
        if debug_pathbuf == format!("\"{}\"", c) {
            continue; // passes through literally
        }
        if named.contains(&c) {
            continue; // named escape, emitted by the caller
        }
        assert_ne!(c, '\'', "Rust Debug must never escape a single quote");
        assert_eq!(
            debug_pathbuf,
            format!("\"\\u{{{:x}}}\"", cp),
            "U+{:04X} escapes to an unexpected form",
            cp
        );
        match ranges.last_mut() {
            Some(last) if last.1 + 1 == cp => last.1 = cp,
            _ => ranges.push((cp, cp)),
        }
    }
    assert_eq!(
        str_pathbuf_divergences, 0,
        "PathBuf and str Debug must agree for single valid scalars"
    );

    println!("// GENERATED by Scripts/rust-debug/generate.sh (rustc ground truth) — do not edit.");
    println!("// Toolchain: {}", toolchain);
    println!("// The ranges encode THIS toolchain's Unicode printability data. A newer");
    println!("// rustc may silently shift the table (the 24-row battery would not catch");
    println!("// a printability flip on an untested codepoint): regenerate only with the");
    println!("// pinned toolchain, and treat any table diff under a newer one as a");
    println!("// deliberate, reviewed change.");
    println!("//");
    println!("// The inclusive Unicode scalar ranges that Rust's `Debug` formatting");
    println!("// of a string renders as `\\u{{<lowercase hex>}}`: every scalar that is");
    println!("// not printable per Rust's `is_printable` table (general categories Cc,");
    println!("// Cf, Cs, Co, Cn, Zl, Zp) or that carries the Grapheme_Extend property");
    println!("// (combining marks, ZWJ, …), EXCLUDING the named escapes");
    println!("// (`\\t` `\\r` `\\n` `\\\\` `\\\"` `\\0`) that");
    println!("// `ContentHasher.rustDebugQuotedSymlink` emits itself. Single quotes are");
    println!("// NOT in this set: Rust `{{:?}}` never escapes `'` (verified by the");
    println!("// generator's assertion sweep over all scalars).");
    println!("//");
    println!(
        "// Sweep source: `format!(\"{{:?}}\", PathBuf::from(c.to_string()))` for every"
    );
    println!("// scalar 0x0...0x10FFFF; PathBuf and str Debug agreed everywhere.");
    println!("enum RustDebugEscapes {{");
    println!("    /// Sorted, inclusive, non-overlapping `(lo, hi)` scalar ranges.");
    println!("    static let unicodeEscapeRanges: [(lo: UInt32, hi: UInt32)] = [");

    let tuples: Vec<String> = ranges
        .iter()
        .map(|(lo, hi)| format!("(0x{:x}, 0x{:x})", lo, hi))
        .collect();
    let mut line = String::from("        ");
    for (index, tuple) in tuples.iter().enumerate() {
        let piece = if index + 1 == tuples.len() {
            tuple.clone()
        } else {
            format!("{}, ", tuple)
        };
        if line.len() + piece.len() > 96 {
            println!("{}", line.trim_end());
            line = String::from("        ");
        }
        line.push_str(&piece);
    }
    if line.trim() != "" {
        println!("{}", line.trim_end());
    }

    println!("    ]");
    println!();
    println!("    /// Binary search: does `scalar` require the `\\u{{…}}` form?");
    println!("    static func needsUnicodeEscape(_ scalar: Unicode.Scalar) -> Bool {{");
    println!("        var low = unicodeEscapeRanges.startIndex");
    println!("        var high = unicodeEscapeRanges.endIndex");
    println!("        while low < high {{");
    println!("            let mid = low + (high - low) / 2");
    println!("            let range = unicodeEscapeRanges[mid]");
    println!("            if scalar.value < range.lo {{");
    println!("                high = mid");
    println!("            }} else if scalar.value > range.hi {{");
    println!("                low = mid + 1");
    println!("            }} else {{");
    println!("                return true");
    println!("            }}");
    println!("        }}");
    println!("        return false");
    println!("    }}");
    println!("}}");
    eprintln!(
        "table: {} ranges covering the \\u{{...}} escape set",
        ranges.len()
    );
}

fn main() {
    match std::env::args().nth(1).as_deref() {
        Some("battery") => battery(),
        Some("table") => {
            let toolchain = std::env::args()
                .nth(2)
                .unwrap_or_else(|| "unknown (pass `rustc --version` output)".to_string());
            table(&toolchain)
        }
        other => {
            eprintln!("usage: rust-debug [battery|table], got {:?}", other);
            std::process::exit(2);
        }
    }
}
