import Foundation
import Testing

@testable import SukiruCore

/// Seam-A end-to-end corpus validation (feature `seam-a-corpus-validation`).
///
/// Every FIX-* and CM-* fixture tree — plus `scope-isolation` — is scanned
/// through the REAL `sukiru-cli` binary and its full report is compared
/// byte-for-byte against the committed, path-normalized expectation snapshot
/// in `Fixtures/expectations/`. The CM-* trees are generated by
/// `Scripts/fixtures/generate.sh` driving the pinned skills@1.5.26 CLI and gh
/// in sandboxes; the FIX-* trees by `build-handbuilt.sh`.
///
/// Record/refresh snapshots after intentional engine or corpus changes:
///   SUKIRU_UPDATE_SNAPSHOTS=1 swift test --filter CorpusExpectationTests
///
/// Note: the FIX-GARBAGE snapshot reflects the CHECKED-IN (readable) tree;
/// the chmod-000 defect that git cannot store is covered by a dedicated test
/// on a chmodded copy (see `garbageUnreadableDirectory`).
@Suite("Corpus expectation snapshots")
struct CorpusExpectationTests {
    /// The parameterized corpus: every checked-in FIX-*/CM-* directory plus
    /// scope-isolation (the VAL-SCAN-007 tree). Discovered from disk so a new
    /// fixture without a recorded snapshot fails loudly.
    static let corpus: [String] = discoverCorpus()

    private static func discoverCorpus() -> [String] {
        let fileManager = FileManager.default
        let entries =
            (try? fileManager.contentsOfDirectory(atPath: FixturePaths.root.path)) ?? []
        let generated = entries.filter { name in
            var isDirectory: ObjCBool = false
            let path = FixturePaths.root.appendingPathComponent(name).path
            guard fileManager.fileExists(atPath: path, isDirectory: &isDirectory),
                isDirectory.boolValue
            else { return false }
            return name.hasPrefix("FIX-") || name.hasPrefix("CM-")
        }
        return (generated + ["scope-isolation"]).sorted()
    }

    // MARK: parameterized snapshot equality (every corpus fixture)

    @Test("Scan matches the committed expectation snapshot", arguments: corpus)
    func snapshotMatches(fixture: String) throws {
        let result = try CLIRunner.scanFixture(fixture)
        let stderr = String(bytes: result.stderr, encoding: .utf8) ?? ""
        try #require(
            result.exitCode == 0,
            "scan of \(fixture) exited \(result.exitCode); stderr: \(stderr)"
        )
        let actual = ExpectationSnapshot.normalize(
            String(bytes: result.stdout, encoding: .utf8) ?? "",
            fixtureBase: FixturePaths.tree(fixture)
        )
        if ExpectationSnapshot.recordMode {
            try ExpectationSnapshot.record(actual, for: fixture)
        }
        let snapshotURL = ExpectationSnapshot.url(for: fixture)
        try #require(
            FileManager.default.fileExists(atPath: snapshotURL.path),
            "missing snapshot for \(fixture); record with SUKIRU_UPDATE_SNAPSHOTS=1"
        )
        let expected = try String(contentsOf: snapshotURL, encoding: .utf8)
        let divergence = ExpectationSnapshot.firstDivergence(actual, expected) ?? ""
        #expect(
            actual == expected,
            "snapshot mismatch for \(fixture) at \(divergence)"
        )
    }

    // MARK: VAL-SCAN-041 — benign trees produce zero actionable findings

    @Test("VAL-SCAN-041a: FIX-EMPTY scans clean — no content, no findings, no issues")
    func emptyTreeIsBenign() throws {
        let report = try CLIRunner.scanReport("FIX-EMPTY")
        #expect(report.schemaVersion == ScanReport.currentSchemaVersion)
        #expect(report.skills.isEmpty)
        #expect(report.skills.flatMap(\.placements).isEmpty)
        #expect(report.findings.isEmpty)
        #expect(report.issues.isEmpty)
    }

    @Test("VAL-SCAN-041b: FIX-CLEAN (one physical placement per name) yields zero findings")
    func cleanTreeHasNoFindings() throws {
        let report = try CLIRunner.scanReport("FIX-CLEAN")
        #expect(!report.skills.isEmpty)
        #expect(report.findings.isEmpty)
        #expect(report.issues.isEmpty)
    }

    // MARK: VAL-SCAN-042 — garbage-everything robustness

    @Test("VAL-SCAN-042: every statically-planted defect is reported, exit 0")
    func garbageCoverage() throws {
        let report = try CLIRunner.scanReport("FIX-GARBAGE")

        // The healthy control skill is inventoried as ownerless.
        let survivor = try #require(report.skills.first { $0.name == "survivor" })
        #expect(survivor.ownership == .ownerless)

        // Malformed SKILL.md and truncated lock each surface as their own issue.
        let issueKinds = Set(report.issues.map(\.kind))
        #expect(issueKinds.contains(IssueKind.skillMDInvalid))
        #expect(issueKinds.contains(IssueKind.ledgerUnreadable))
        let issuePaths = report.issues.map(\.path)
        #expect(issuePaths.contains { $0.contains("nameless/SKILL.md") })
        #expect(issuePaths.contains { $0.hasSuffix(".agents/.skill-lock.json") })

        // The malformed nameless skill never becomes a placement, and stray
        // non-skill files are never placements either.
        let names = report.skills.map(\.name)
        #expect(!names.contains("nameless"))
        #expect(!names.contains("no-skill-md"))
        let placementPaths = report.skills.flatMap(\.placements).map(\.path)
        #expect(placementPaths.allSatisfy { !$0.hasSuffix("README.txt") })
        #expect(placementPaths.allSatisfy { !$0.hasSuffix("loose.bin") })

        // The dangling symlink is inventoried as brokenSymlink AND reported.
        let rotted = report.skills.flatMap(\.placements).filter {
            $0.path.contains("rotted")
        }
        #expect(rotted.count == 1)
        #expect(rotted.first?.kind == .brokenSymlink)
        #expect(!report.findings(rule: "broken-symlink").isEmpty)
    }

    @Test("VAL-SCAN-042: an unreadable directory is an issue and suppresses nothing")
    func garbageUnreadableDirectory() throws {
        let fileManager = FileManager.default
        let sandbox = try TempTree()
        let copy = sandbox.path + "/FIX-GARBAGE"
        try fileManager.copyItem(atPath: FixturePaths.tree("FIX-GARBAGE"), toPath: copy)
        let lockedDir = copy + "/.agents/skills/locked-dir"
        // git cannot store a chmod-000 directory (Scripts/fixtures/
        // prepare-runtime.sh); apply the runtime state on the throwaway copy.
        try fileManager.setAttributes([.posixPermissions: 0o000], ofItemAtPath: lockedDir)
        defer {
            // Restore readability so TempTree's deinit can remove the copy.
            try? fileManager.setAttributes([.posixPermissions: 0o755], ofItemAtPath: lockedDir)
        }

        let result = try CLIRunner.run(
            ["scan", "--format", "json"],
            environment: CLIRunner.fixtureEnvironment(home: copy)
        )
        let stderr = String(bytes: result.stderr, encoding: .utf8) ?? ""
        try #require(result.exitCode == 0, "scan exited \(result.exitCode); stderr: \(stderr)")
        let report = try JSONDecoder().decode(ScanReport.self, from: result.stdout)

        // The unreadable dir surfaces as an issue naming the path...
        #expect(report.issues.contains { $0.path.contains("locked-dir") })
        // ...while every other planted defect is still reported.
        #expect(report.skills.contains { $0.name == "survivor" })
        #expect(report.issues.contains { $0.kind == IssueKind.ledgerUnreadable })
        #expect(!report.findings(rule: "broken-symlink").isEmpty)
    }
}
