import Foundation
import Testing

@testable import SukiruCore

/// `ContentHasher` golden digest vectors.
///
/// Every expected digest below was produced independently of the Swift
/// implementation: the `sortcase` vector is the REAL `skills@1.5.26` CLI's
/// own lock value (research/hash-algorithm.md §8, fixture preserved from the
/// research sandbox); the symlink vectors quote their `symlink:"<target>"`
/// bytes with rustc 1.98.0 ITSELF as the oracle (`format!("symlink:{:?}",
/// PathBuf)`) via Scripts/rust-debug/generate.sh, composed into a digest by
/// the Node reference (port-reference trap #7). They pin byte-exactness of
/// the digest construction: SHA-256 over `utf8(relativePath) + bytes`,
/// sorted by ICU collation, no separators.
@Suite("Content hasher golden vectors")
struct ContentHasherVectorTests {
    private let hasher = ContentHasher()

    private func hash(of result: Result<String, ScanIssue>) -> String? {
        if case .success(let hex) = result { return hex }
        return nil
    }

    private func files(of result: Result<[SkillFile], ScanIssue>) -> [SkillFile]? {
        if case .success(let files) = result { return files }
        return nil
    }

    @Test("Golden sortcase vector matches the real CLI's computedHash")
    func goldenSortcaseVector() throws {
        let tree = try TempTree()
        let skill = "skills/sortcase"
        try tree.file(
            "\(skill)/SKILL.md",
            contents: "---\nname: sortcase\n"
                + "description: A fixture skill used to prove file ordering in the hash.\n"
                + "---\nbody\n"
        )
        try tree.file("\(skill)/scripts/run.sh", contents: "aaa\n")
        try tree.file("\(skill)/_notes.md", contents: "bbb\n")
        try tree.file("\(skill)/Zebra.md", contents: "ccc\n")
        try tree.file("\(skill)/apple.md", contents: "ddd\n")

        let result = hasher.computedHash(ofSkillAtPath: "\(tree.path)/\(skill)")
        #expect(
            hash(of: result)
                == "4db3d555c1b5224c98042b82b7b2bcf9479f77898dcd8abd950a45d0f2371281"
        )

        // The same tree pins the ICU file order (Node localeCompare output).
        let collected = try #require(files(of: hasher.skillFiles(atPath: "\(tree.path)/\(skill)")))
        let expectedOrder =
            "_notes.md\napple.md\nscripts/run.sh\nSKILL.md\nZebra.md"
            .split(separator: "\n").map(String.init)
        #expect(collected.map(\.relativePath) == expectedOrder)
    }

    @Test("Symlinks hash as symlink:\"<target>\" and are never traversed")
    func symlinksHashAsDebugQuotedTarget() throws {
        let tree = try TempTree()
        let skill = "skills/linky"
        try tree.file(
            "\(skill)/SKILL.md",
            contents: "---\nname: linky\ndescription: Symlink hashing.\n---\nbody\n"
        )
        try tree.file("\(skill)/target/one.md", contents: "payload\n")
        try tree.file("\(skill)/target/sub/two.md", contents: "nested\n")
        try tree.symlink("\(skill)/ref.txt", to: "target/one.md")
        try tree.symlink("\(skill)/dirlink", to: "target")

        let result = hasher.computedHash(ofSkillAtPath: "\(tree.path)/\(skill)")
        // Independent Node reference (Rust-Debug quoting, symlinked dirs not
        // descended).
        #expect(
            hash(of: result)
                == "ed67f458e692462d6a69bfdcae895e2a8ae968e6e4a5091538504f55ff3efcb5"
        )

        let collected = try #require(files(of: hasher.skillFiles(atPath: "\(tree.path)/\(skill)")))
        let byPath = Dictionary(
            uniqueKeysWithValues: collected.map { ($0.relativePath, $0.bytes) })
        #expect(byPath["ref.txt"] == Data(#"symlink:"target/one.md""#.utf8))
        #expect(byPath["dirlink"] == Data(#"symlink:"target""#.utf8))
        // The symlinked directory contributes no descendant entries.
        #expect(!collected.contains { $0.relativePath.hasPrefix("dirlink/") })
    }

    @Test("Symlink target quoting follows Rust Debug escaping")
    func symlinkTargetEscapingMatchesRustDebug() throws {
        let tree = try TempTree()
        let skill = "skills/esc"
        try tree.file(
            "\(skill)/SKILL.md",
            contents: "---\nname: esc\ndescription: Escape quoting.\n---\n"
        )
        // Double quote, backslash, single quote in one name. Rust Debug
        // escapes the first two but NEVER the single quote; the backslash in
        // the FILE's own relative path becomes '/' (upstream's `\` → `/`
        // normalization applies to names).
        let weird = "we\"ird\\it's.md"
        try tree.file("\(skill)/\(weird)", contents: "x\n")
        try tree.symlink("\(skill)/esc.txt", to: weird)

        let result = hasher.computedHash(ofSkillAtPath: "\(tree.path)/\(skill)")
        // Golden digest regenerated by Scripts/rust-debug/generate.sh: the
        // symlink bytes below are rustc 1.98.0's own `{:?}` output, composed
        // by Scripts/rust-debug/esc-fixture-digest.mjs (Node ICU ordering +
        // SHA-256 around the rustc-quoted bytes).
        #expect(
            hash(of: result)
                == "0a197f1e1f2f33da05996938ec4dcae2cfedbb402a3b18ef928b07ca4b049de7"
        )

        let collected = try #require(files(of: hasher.skillFiles(atPath: "\(tree.path)/\(skill)")))
        let byPath = Dictionary(
            uniqueKeysWithValues: collected.map { ($0.relativePath, $0.bytes) })
        #expect(byPath["esc.txt"] == Data(#"symlink:"we\"ird\\it's.md""#.utf8))
        #expect(byPath[#"we"ird/it's.md"#] == Data("x\n".utf8))
    }

    @Test("Rust-Debug quoting byte-matches rustc for adversarial targets")
    func rustDebugQuotingMatchesRustcBattery() {
        for row in rustDebugBattery {
            let actual = ContentHasher.rustDebugQuotedSymlink(row.target)
            #expect(
                actual == row.expected,
                "\(row.name): \(actual.debugDescription) != \(row.expected.debugDescription)"
            )
        }
    }

    @Test("Empty skill directory hashes as SHA-256 of the empty input")
    func emptyDirectory() throws {
        let tree = try TempTree()
        try tree.dir("skills/empty")
        let result = hasher.computedHash(ofSkillAtPath: "\(tree.path)/skills/empty")
        #expect(
            hash(of: result)
                == "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"
        )
    }

    @Test("Empty files contribute their relative path only")
    func emptyFileContributesPathOnly() throws {
        let tree = try TempTree()
        try tree.file("skills/p/only.txt", contents: "")
        // sha256("only.txt") — the path bytes with zero content bytes.
        let result = hasher.computedHash(ofSkillAtPath: "\(tree.path)/skills/p")
        #expect(
            hash(of: result)
                == "08c87c8e2482e76b2bd1f7c30898a8cc7a7b66b67cc8e331b6e0a49ca8c64207"
        )
    }
}

/// One rustc ground-truth row: an adversarial symlink target and the exact
/// bytes of `format!("symlink:{target:?}", PathBuf)` for it.
private struct RustDebugBatteryRow {
    let name: String
    let targetHex: String
    let expectedHex: String

    var target: String { Self.decode(targetHex) }
    var expected: String { Self.decode(expectedHex) }

    private static func decode(_ hex: String) -> String {
        var bytes: [UInt8] = []
        var index = hex.startIndex
        while index < hex.endIndex {
            let next = hex.index(index, offsetBy: 2)
            bytes.append(UInt8(hex[index..<next], radix: 16) ?? 0)
            index = next
        }
        guard let string = String(bytes: bytes, encoding: .utf8) else {
            preconditionFailure("battery rows are valid UTF-8 hex")
        }
        return string
    }
}

// swift-format REQUIRES the trailing comma swiftlint forbids in multi-line
// collection literals (known gate conflict) — suppress for this array only.
// swiftlint:disable trailing_comma
/// Ground truth produced BY rustc 1.98.0 (`format!("symlink:{:?}",
/// PathBuf::from(target))`) via Scripts/rust-debug/generate.sh — never
/// hand-computed; regenerate, don't edit. Covers: named escapes, NUL → `\0`,
/// single quote passing through literally, grapheme-extended scalars
/// (combining marks, ZWJ/ZWNJ) and non-printable scalars (NEL, soft hyphen,
/// NBSP, BOM, separators, private-use, unassigned, tag chars) rendered
/// `\u{<lower-hex>}`, and printable non-ASCII (CJK, emoji, astral) passing
/// through unescaped.
private let rustDebugBattery: [RustDebugBatteryRow] = [
    RustDebugBatteryRow(
        name: "plain", targetHex: "7461726765742f6f6e652e6d64",
        expectedHex: "73796d6c696e6b3a227461726765742f6f6e652e6d6422"),
    RustDebugBatteryRow(
        name: "quote-backslash-squote", targetHex: "7765226972645c697427732e6d64",
        expectedHex: "73796d6c696e6b3a2277655c226972645c5c697427732e6d6422"),
    RustDebugBatteryRow(
        name: "squote-only", targetHex: "697427732e6d64",
        expectedHex: "73796d6c696e6b3a22697427732e6d6422"),
    RustDebugBatteryRow(
        name: "nul", targetHex: "6e756c0062797465",
        expectedHex: "73796d6c696e6b3a226e756c5c306279746522"),
    RustDebugBatteryRow(
        name: "tab", targetHex: "74610962",
        expectedHex: "73796d6c696e6b3a2274615c746222"),
    RustDebugBatteryRow(
        name: "cr", targetHex: "63610d72",
        expectedHex: "73796d6c696e6b3a2263615c727222"),
    RustDebugBatteryRow(
        name: "lf", targetHex: "6c690a6e65",
        expectedHex: "73796d6c696e6b3a226c695c6e6e6522"),
    RustDebugBatteryRow(
        name: "del", targetHex: "64656c7f657465",
        expectedHex: "73796d6c696e6b3a2264656c5c757b37667d65746522"),
    RustDebugBatteryRow(
        name: "nel", targetHex: "6e65c2856c",
        expectedHex: "73796d6c696e6b3a226e655c757b38357d6c22"),
    RustDebugBatteryRow(
        name: "soft-hyphen", targetHex: "736fc2ad6674",
        expectedHex: "73796d6c696e6b3a22736f5c757b61647d667422"),
    RustDebugBatteryRow(
        name: "nfd-combining-acute", targetHex: "7265cc8173756d65cc81",
        expectedHex: "73796d6c696e6b3a2272655c757b3330317d73756d655c757b3330317d22"),
    RustDebugBatteryRow(
        name: "combining-only", targetHex: "cc81cd81",
        expectedHex: "73796d6c696e6b3a225c757b3330317d5c757b3334317d22"),
    RustDebugBatteryRow(
        name: "zwj", targetHex: "61e2808d62",
        expectedHex: "73796d6c696e6b3a22615c757b323030647d6222"),
    RustDebugBatteryRow(
        name: "zwnj", targetHex: "61e2808c62",
        expectedHex: "73796d6c696e6b3a22615c757b323030637d6222"),
    RustDebugBatteryRow(
        name: "bom", targetHex: "61efbbbf62",
        expectedHex: "73796d6c696e6b3a22615c757b666566667d6222"),
    RustDebugBatteryRow(
        name: "nbsp", targetHex: "61c2a062",
        expectedHex: "73796d6c696e6b3a22615c757b61307d6222"),
    RustDebugBatteryRow(
        name: "line-separator", targetHex: "61e280a862",
        expectedHex: "73796d6c696e6b3a22615c757b323032387d6222"),
    RustDebugBatteryRow(
        name: "paragraph-separator", targetHex: "61e280a962",
        expectedHex: "73796d6c696e6b3a22615c757b323032397d6222"),
    RustDebugBatteryRow(
        name: "private-use", targetHex: "61ee808062",
        expectedHex: "73796d6c696e6b3a22615c757b653030307d6222"),
    RustDebugBatteryRow(
        name: "unassigned", targetHex: "61cdb862",
        expectedHex: "73796d6c696e6b3a22615c757b3337387d6222"),
    RustDebugBatteryRow(
        name: "tag-char", targetHex: "61f3a0808162",
        expectedHex: "73796d6c696e6b3a22615c757b65303030317d6222"),
    RustDebugBatteryRow(
        name: "cjk", targetHex: "e4b8ade696872e6d64",
        expectedHex: "73796d6c696e6b3a22e4b8ade696872e6d6422"),
    RustDebugBatteryRow(
        name: "emoji", targetHex: "6372616220f09fa6802e6d64",
        expectedHex: "73796d6c696e6b3a226372616220f09fa6802e6d6422"),
    RustDebugBatteryRow(
        name: "astral-musical", targetHex: "f09d849e2e6d64",
        expectedHex: "73796d6c696e6b3a22f09d849e2e6d6422"),
]
// swiftlint:enable trailing_comma
